# Generated by Django 5.2.6 on 2025-09-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pakaian', 'Pakaian'), ('aksesoris', 'Aksesoris'), ('sepatu', 'Sepatu'), ('bola', 'Bola')], max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
