# Generated by Django 5.2.6 on 2025-09-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pakaian', 'Pakaian'), ('aksesoris', 'Aksesoris'), ('sepatu', 'Sepatu'), ('bola', 'Bola')], max_length=20),
        ),
    ]
